<style>
#tracy-debug .nette-sessionPanel h1 {
	min-width: 400px;
}

#tracy-debug .nette-sessionPanel h2 {
	font: 11pt/1.5 sans-serif;
	margin: 0;
	padding: 2px 8px;
	background: #3484d2;
	color: white;
}

#tracy-debug .nette-sessionPanel small {
	font-size: 70%;
}

#tracy-debug .nette-sessionPanel .nette-inner{
    overflow: auto;
    max-height: 600px;
    max-width: 700px;
}

#tracy-debug .nette-sessionPanel table {
	width: 100%;
	white-space: nowrap;
}

#tracy-debug .nette-sessionPanel td.nette-session {
	font-weight: bold;
}

#tracy-debug .nette-sessionPanel .section-type {
	font-size: 85%;
	color: #999;
}

#tracy-debug .nette-sessionPanel .remove b {
	line-height: 20px;
	cursor: pointer;
	-webkit-appearance: none;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	font-size: 20px;
	font-weight: bold;
	line-height: 20px;
	color: black;
	text-shadow: 0 1px 0 white;
	opacity: 0.2;
	vertical-align: bottom;
	text-decoration: none;
}

#tracy-debug .nette-sessionPanel .remove a:hover {
	background: transparent;
	color: #125EAE;
}

#tracy-debug .nette-sessionPanel .remove a:hover span {
	text-decoration: underline;
}
</style>

<div class="nette-sessionPanel">
	<h1>Session <small>(Max lifetime: <?php echo $time($sessionMaxTime); ?>)</small></h1>
	<div class="nette-inner">
		<table>
			<thead><tr><th>Name</th><th>Data</th><th>Expires in</th><th></th></tr></thead>
			<tbody>
			<?php foreach ($sections as $section): ?>
				<tr>
					<td class="title <?php echo $section->sectionType; ?>" width="10%">
						<?php echo $esc($section->title); ?>
						<?php if ($section->sectionType == 'php-session'): ?>
							<span class="section-type">php section</span>
						<?php endif; ?>
					</td>
					<td><?php echo $click($section->data); ?></td>
					<td width="5%"><?php echo $esc($section->expiration); ?></td>
					<td width="1%" class="remove"><a href="<?php echo $esc($del($section->title, $section->sectionType)); ?>"><b>×</b></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>

		<p class="remove"><a href="<?php echo $esc($del()); ?>"><b>×</b> <span>Delete whole session</span></a></p>
	</div>
</div>
